<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Description>Planet Ministries Theme for Oqtane</Description>
    <AssemblyName>Ncube.Theme.PlanetMinistries.Client.Oqtane</AssemblyName>
    <BlazorWebAssemblyEnableLinking>false</BlazorWebAssemblyEnableLinking>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="9.0.4" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Authentication" Version="9.0.4" />
    <PackageReference Include="Microsoft.Extensions.Localization" Version="9.0.4" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Oqtane.Client" Version="6.1.2" />
    <PackageReference Include="Oqtane.Shared" Version="6.1.2" />
  </ItemGroup>

</Project>